packages:
  - apps/*
  - packages/*

allowBuilds:
  "@heroui-pro/react": true
  "@nestjs/core": false
  "@parcel/watcher": false
  "@prisma/engines": false
  "@swc/core": false
  "@zowe/secrets-for-zowe-sdk": false
  cbor-extract: false
  core-js: false
  esbuild: false
  heroui-native-pro: true
  heroui-pro: true
  prisma: false
  protobufjs: false
  sharp: false

catalog:
  "@ai-sdk/gateway": 4.0.46
  "@ai-sdk/openai": 4.0.36
  "@ai-sdk/otel": 1.0.58
  "@better-auth/drizzle-adapter": 1.7.2
  "@heroui/react": 3.2.4
  "@heroui/styles": 3.2.4
  "@langfuse/otel": 5.3.0
  "@tailwindcss/postcss": 4.3.0
  "@types/node": 24.13.2
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@upstash/redis": 1.38.0
  "@vercel/related-projects": 1.1.0
  "@vitest/coverage-v8": 5.0.0
  "@vitest/ui": 5.0.0
  ai: 7.0.58
  better-auth: 1.7.2
  date-fns: 4.1.0
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  next: 16.3.0
  react: 19.2.6
  react-dom: 19.2.6
  sonner: 2.0.7
  tailwindcss: 4.3.0
  tsx: 4.21.0
  typescript: 7.0.2
  vitest: 5.0.0
  zod: 4.4.3

savePrefix: ""
