packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.32
  '@langfuse/otel': ^4.4.2
  '@types/node': ^22.16.4
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitest/coverage-v8': ^3.2.4
  ai: ^5.0.52
  date-fns: ^3.6.0
  next: ^16.0.3
  react: ^19.2.0
  react-dom: ^19.2.0
  resend: ^6.1.2
  sonner: ^2.0.7
  superjson: ^2.2.2
  typescript: ^5.8.3
  vitest: 3.2.4
  zod: ^3.25.76

overrides:
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
