const BASE_SECRETS = [
  "UPDATER_API_TOKEN",
  "DATABASE_URL",
  "SG_CARS_TRENDS_API_TOKEN",
] as const;

const DISCORD_SECRETS = [
  "DISCORD_WEBHOOK_URL",
  "DISCORD_WORKFLOW_WEBHOOK_URL",
] as const;

const LINKEDIN_SECRETS = [
  "LINKEDIN_CLIENT_ID",
  "LINKEDIN_CLIENT_SECRET",
  "LINKEDIN_ACCESS_TOKEN",
  "LINKEDIN_REFRESH_TOKEN",
  "LINKEDIN_ORGANISATION_ID",
  "LINKEDIN_USER_ID",
] as const;

const TELEGRAM_SECRETS = ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHANNEL_ID"] as const;

const TWITTER_SECRETS = [
  "TWITTER_APP_KEY",
  "TWITTER_APP_SECRET",
  "TWITTER_ACCESS_TOKEN",
  "TWITTER_ACCESS_SECRET",
] as const;

const UPSTASH_SECRETS = [
  "QSTASH_CURRENT_SIGNING_KEY",
  "QSTASH_NEXT_SIGNING_KEY",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
] as const;

export const SECRET_KEYS = [
  ...BASE_SECRETS,
  ...DISCORD_SECRETS,
  ...LINKEDIN_SECRETS,
  ...TELEGRAM_SECRETS,
  ...TWITTER_SECRETS,
  ...UPSTASH_SECRETS,
  "GEMINI_API_KEY",
] as const;

export const secrets = Object.fromEntries(
  SECRET_KEYS.map((key) => [key, new sst.Secret(key, process.env[key])]),
);
