export const BASE_SECRETS = ["UPDATER_API_TOKEN", "DATABASE_URL"];

// "FACEBOOK_ACCESS_TOKEN",

export const DISCORD_SECRETS = ["DISCORD_WEBHOOK_URL"] as const;

export const LINKEDIN_SECRETS = [
  "LINKEDIN_CLIENT_ID",
  "LINKEDIN_CLIENT_SECRET",
  "LINKEDIN_ACCESS_TOKEN",
  "LINKEDIN_ORGANISATION_ID",
  "LINKEDIN_USER_ID",
] as const;

export const TWITTER_SECRETS = [
  "TWITTER_APP_KEY",
  "TWITTER_APP_SECRET",
  "TWITTER_ACCESS_TOKEN",
  "TWITTER_ACCESS_SECRET",
] as const;

export const UPSTASH_SECRETS = [
  "QSTASH_CURRENT_SIGNING_KEY",
  "QSTASH_NEXT_SIGNING_KEY",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
] as const;

export const SECRET_KEYS = [
  ...BASE_SECRETS,
  ...DISCORD_SECRETS,
  ...LINKEDIN_SECRETS,
  ...TWITTER_SECRETS,
  ...UPSTASH_SECRETS,
];
