name: Run Database Migrations

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment name"
        required: true
        type: string

env:
  HEROUI_AUTH_TOKEN: ${{ secrets.HEROUI_AUTH_TOKEN }}

permissions:
  contents: read
  packages: read

jobs:
  run-migrations:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
    concurrency:
      group: migrations-${{ inputs.environment }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:



      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run migrations
        working-directory: ./packages/database
        run: pnpm migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
